### ISSUE TITLE
Create a new thomascookmoney.com website

### ISSUE THREAD

**Issue by plaenen** [tcm-labs/identity#8]
As a business we want to upgrade our thomascook money website

- To provide a better customer experience
- To ensure we offer all services on the website in a secure and compliant way

Statement of work

__MVP__

- [ ] Create a marketing website for Thomas Cook Money
- [ ] Create a set of micro-apps
  - [ ] Reserve Currency
  - [ ] Rate watch
  - [ ] Store Finder 
- [ ] Embed the micro-apps on the Thomas Cook Money Website

__After MVP Roadmap__

- [ ] Embed the micro-apps on the Thomas Cook Website
- [ ] Embed the micro-apps in companion app
- [ ]
